server:
  port: 8080
  servlet:
    context-path: /

  compression:
    enabled: true
    min-response-size: 1
    mime-types: application/json

session:
  expire:
    time: 3
spring:
  application:
    name: spring-session
  http:
    encoding:
      force: true
      enabled: true
      charset: utf-8
  redis:
    host: 139.9.95.160
    password: Root@123
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848